# [covid]

In [0]:
USE [master]
GO

In [0]:
/****** Object:  Database [covid]    Script Date: 16/05/2024 02:58:19 ******/
CREATE DATABASE [covid]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'covid', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\covid.mdf' , SIZE = 139264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'covid_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\covid_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [covid] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [covid].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [covid] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [covid] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [covid] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [covid] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [covid] SET ARITHABORT OFF 
GO
ALTER DATABASE [covid] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [covid] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [covid] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [covid] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [covid] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [covid] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [covid] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [covid] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [covid] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [covid] SET  DISABLE_BROKER 
GO
ALTER DATABASE [covid] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [covid] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [covid] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [covid] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [covid] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [covid] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [covid] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [covid] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [covid] SET  MULTI_USER 
GO
ALTER DATABASE [covid] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [covid] SET DB_CHAINING OFF 
GO
ALTER DATABASE [covid] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [covid] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [covid] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [covid] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [covid] SET QUERY_STORE = ON
GO
ALTER DATABASE [covid] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

# [dbo].[Death]

In [0]:
USE [covid]
GO

In [0]:
/****** Object:  Table [dbo].[Death]    Script Date: 16/05/2024 02:58:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Death](
	[iso_code] [nvarchar](255) NULL,
	[continent] [nvarchar](255) NULL,
	[location] [nvarchar](255) NULL,
	[date] [datetime] NULL,
	[total_cases] [float] NULL,
	[new_cases] [float] NULL,
	[new_cases_smoothed] [float] NULL,
	[total_deaths] [nvarchar](255) NULL,
	[new_deaths] [nvarchar](255) NULL,
	[new_deaths_smoothed] [float] NULL,
	[total_cases_per_million] [float] NULL,
	[new_cases_per_million] [float] NULL,
	[new_cases_smoothed_per_million] [float] NULL,
	[total_deaths_per_million] [nvarchar](255) NULL,
	[new_deaths_per_million] [nvarchar](255) NULL,
	[new_deaths_smoothed_per_million] [float] NULL,
	[reproduction_rate] [nvarchar](255) NULL,
	[icu_patients] [nvarchar](255) NULL,
	[icu_patients_per_million] [nvarchar](255) NULL,
	[hosp_patients] [nvarchar](255) NULL,
	[hosp_patients_per_million] [nvarchar](255) NULL,
	[weekly_icu_admissions] [nvarchar](255) NULL,
	[weekly_icu_admissions_per_million] [nvarchar](255) NULL,
	[weekly_hosp_admissions] [nvarchar](255) NULL,
	[weekly_hosp_admissions_per_million] [nvarchar](255) NULL,
	[new_tests] [nvarchar](255) NULL,
	[total_tests] [nvarchar](255) NULL,
	[total_tests_per_thousand] [nvarchar](255) NULL,
	[new_tests_per_thousand] [nvarchar](255) NULL,
	[new_tests_smoothed] [nvarchar](255) NULL,
	[new_tests_smoothed_per_thousand] [nvarchar](255) NULL,
	[positive_rate] [nvarchar](255) NULL,
	[tests_per_case] [nvarchar](255) NULL,
	[tests_units] [nvarchar](255) NULL,
	[total_vaccinations] [nvarchar](255) NULL,
	[people_vaccinated] [nvarchar](255) NULL,
	[people_fully_vaccinated] [nvarchar](255) NULL,
	[new_vaccinations] [nvarchar](255) NULL,
	[new_vaccinations_smoothed] [nvarchar](255) NULL,
	[total_vaccinations_per_hundred] [nvarchar](255) NULL,
	[people_vaccinated_per_hundred] [nvarchar](255) NULL,
	[people_fully_vaccinated_per_hundred] [nvarchar](255) NULL,
	[new_vaccinations_smoothed_per_million] [nvarchar](255) NULL,
	[stringency_index] [float] NULL,
	[population] [float] NULL,
	[population_density] [float] NULL,
	[median_age] [float] NULL,
	[aged_65_older] [float] NULL,
	[aged_70_older] [float] NULL,
	[gdp_per_capita] [float] NULL,
	[extreme_poverty] [nvarchar](255) NULL,
	[cardiovasc_death_rate] [float] NULL,
	[diabetes_prevalence] [float] NULL,
	[female_smokers] [nvarchar](255) NULL,
	[male_smokers] [nvarchar](255) NULL,
	[handwashing_facilities] [float] NULL,
	[hospital_beds_per_thousand] [float] NULL,
	[life_expectancy] [float] NULL,
	[human_development_index] [float] NULL
) ON [PRIMARY]
GO

# [dbo].[Vaccinations]

In [0]:
/****** Object:  Table [dbo].[Vaccinations]    Script Date: 16/05/2024 02:58:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Vaccinations](
	[iso_code] [nvarchar](255) NULL,
	[continent] [nvarchar](255) NULL,
	[location] [nvarchar](255) NULL,
	[date] [datetime] NULL,
	[new_tests] [nvarchar](255) NULL,
	[total_tests] [nvarchar](255) NULL,
	[total_tests_per_thousand] [nvarchar](255) NULL,
	[new_tests_per_thousand] [nvarchar](255) NULL,
	[new_tests_smoothed] [nvarchar](255) NULL,
	[new_tests_smoothed_per_thousand] [nvarchar](255) NULL,
	[positive_rate] [nvarchar](255) NULL,
	[tests_per_case] [nvarchar](255) NULL,
	[tests_units] [nvarchar](255) NULL,
	[total_vaccinations] [nvarchar](255) NULL,
	[people_vaccinated] [nvarchar](255) NULL,
	[people_fully_vaccinated] [nvarchar](255) NULL,
	[new_vaccinations] [nvarchar](255) NULL,
	[new_vaccinations_smoothed] [nvarchar](255) NULL,
	[total_vaccinations_per_hundred] [nvarchar](255) NULL,
	[people_vaccinated_per_hundred] [nvarchar](255) NULL,
	[people_fully_vaccinated_per_hundred] [nvarchar](255) NULL,
	[new_vaccinations_smoothed_per_million] [nvarchar](255) NULL,
	[stringency_index] [float] NULL,
	[population_density] [float] NULL,
	[median_age] [float] NULL,
	[aged_65_older] [float] NULL,
	[aged_70_older] [float] NULL,
	[gdp_per_capita] [float] NULL,
	[extreme_poverty] [nvarchar](255) NULL,
	[cardiovasc_death_rate] [float] NULL,
	[diabetes_prevalence] [float] NULL,
	[female_smokers] [nvarchar](255) NULL,
	[male_smokers] [nvarchar](255) NULL,
	[handwashing_facilities] [float] NULL,
	[hospital_beds_per_thousand] [float] NULL,
	[life_expectancy] [float] NULL,
	[human_development_index] [float] NULL
) ON [PRIMARY]
GO

# [covid]

In [0]:
USE [master]
GO

In [0]:
ALTER DATABASE [covid] SET  READ_WRITE 
GO