# [international_debt]

In [0]:
USE [master]
GO

In [0]:
/****** Object:  Database [international_debt]    Script Date: 16/05/2024 03:00:36 ******/
CREATE DATABASE [international_debt]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'international_debt', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\international_debt.mdf' , SIZE = 139264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'international_debt_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\international_debt_log.ldf' , SIZE = 139264KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [international_debt] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [international_debt].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [international_debt] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [international_debt] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [international_debt] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [international_debt] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [international_debt] SET ARITHABORT OFF 
GO
ALTER DATABASE [international_debt] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [international_debt] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [international_debt] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [international_debt] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [international_debt] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [international_debt] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [international_debt] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [international_debt] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [international_debt] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [international_debt] SET  DISABLE_BROKER 
GO
ALTER DATABASE [international_debt] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [international_debt] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [international_debt] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [international_debt] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [international_debt] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [international_debt] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [international_debt] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [international_debt] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [international_debt] SET  MULTI_USER 
GO
ALTER DATABASE [international_debt] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [international_debt] SET DB_CHAINING OFF 
GO
ALTER DATABASE [international_debt] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [international_debt] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [international_debt] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [international_debt] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [international_debt] SET QUERY_STORE = ON
GO
ALTER DATABASE [international_debt] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

# [dbo].[country]

In [0]:
USE [international_debt]
GO

In [0]:
/****** Object:  Table [dbo].[country]    Script Date: 16/05/2024 03:00:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[country](
	[Code] [nvarchar](255) NULL,
	[Long Name] [nvarchar](255) NULL,
	[Income Group] [nvarchar](255) NULL,
	[Region] [nvarchar](255) NULL,
	[Lending category] [nvarchar](255) NULL,
	[Other groups] [nvarchar](255) NULL,
	[Currency Unit] [nvarchar](255) NULL,
	[Latest population census] [nvarchar](255) NULL,
	[Latest household survey] [nvarchar](255) NULL,
	[Special Notes] [nvarchar](max) NULL,
	[National accounts base year] [nvarchar](255) NULL,
	[National accounts reference year] [float] NULL,
	[System of National Accounts] [nvarchar](255) NULL,
	[SNA price valuation] [nvarchar](255) NULL,
	[PPP survey years] [nvarchar](255) NULL,
	[Balance of Payments Manual in use] [nvarchar](255) NULL,
	[External debt Reporting status] [nvarchar](255) NULL,
	[System of trade] [nvarchar](255) NULL,
	[Government Accounting concept] [nvarchar](255) NULL,
	[IMF data dissemination standard] [nvarchar](255) NULL,
	[Source of most recent Income and expenditure data] [nvarchar](255) NULL,
	[Vital registration complete] [nvarchar](255) NULL,
	[Latest agricultural census] [float] NULL,
	[Latest industrial data] [float] NULL,
	[Latest trade data] [float] NULL,
	[Latest water withdrawal data] [float] NULL,
	[2-alpha code] [nvarchar](255) NULL,
	[WB-2 code] [nvarchar](255) NULL,
	[Table Name] [nvarchar](255) NULL,
	[Short Name] [nvarchar](255) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

# [dbo].[Debt]

In [0]:
/****** Object:  Table [dbo].[Debt]    Script Date: 16/05/2024 03:00:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Debt](
	[Country Name] [nvarchar](255) NULL,
	[Country Code] [nvarchar](255) NULL,
	[Series Name] [nvarchar](255) NULL,
	[Series Code] [nvarchar](255) NULL,
	[1970] [nvarchar](255) NULL,
	[1971] [nvarchar](255) NULL,
	[1972] [nvarchar](255) NULL,
	[1973] [nvarchar](255) NULL,
	[1974] [nvarchar](255) NULL,
	[1975] [nvarchar](255) NULL,
	[1976] [nvarchar](255) NULL,
	[1977] [nvarchar](255) NULL,
	[1978] [nvarchar](255) NULL,
	[1979] [nvarchar](255) NULL,
	[1980] [nvarchar](255) NULL,
	[1981] [nvarchar](255) NULL,
	[1982] [nvarchar](255) NULL,
	[1983] [nvarchar](255) NULL,
	[1984] [nvarchar](255) NULL,
	[1985] [nvarchar](255) NULL,
	[1986] [nvarchar](255) NULL,
	[1987] [nvarchar](255) NULL,
	[1988] [nvarchar](255) NULL,
	[1989] [nvarchar](255) NULL,
	[1990] [nvarchar](255) NULL,
	[1991] [nvarchar](255) NULL,
	[1992] [nvarchar](255) NULL,
	[1993] [nvarchar](255) NULL,
	[1994] [nvarchar](255) NULL,
	[1995] [nvarchar](255) NULL,
	[1996] [nvarchar](255) NULL,
	[1997] [nvarchar](255) NULL,
	[1998] [nvarchar](255) NULL,
	[1999] [nvarchar](255) NULL,
	[2000] [nvarchar](255) NULL,
	[2001] [nvarchar](255) NULL,
	[2002] [nvarchar](255) NULL,
	[2003] [nvarchar](255) NULL,
	[2004] [nvarchar](255) NULL,
	[2005] [nvarchar](255) NULL,
	[2006] [float] NULL,
	[2007] [float] NULL,
	[2008] [float] NULL,
	[2009] [float] NULL,
	[2010] [float] NULL,
	[2011] [float] NULL,
	[2012] [float] NULL,
	[2013] [float] NULL,
	[2014] [float] NULL,
	[2015] [float] NULL,
	[2016] [float] NULL,
	[2017] [float] NULL,
	[2018] [float] NULL,
	[2019] [float] NULL,
	[2020] [float] NULL,
	[2021] [float] NULL,
	[2022] [nvarchar](255) NULL,
	[DEBT] [float] NULL
) ON [PRIMARY]
GO

# [dbo].[debt_classes]

In [0]:
/****** Object:  Table [dbo].[debt_classes]    Script Date: 16/05/2024 03:00:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[debt_classes](
	[debtID] [int] NULL,
	[Country Name] [varchar](50) NULL,
	[Country Code] [varchar](50) NULL,
	[Series Name] [varchar](100) NULL,
	[Series Code] [varchar](100) NULL,
	[1970] [int] NULL,
	[1971] [int] NULL,
	[1972] [int] NULL,
	[1973] [int] NULL,
	[1974] [int] NULL,
	[1975] [int] NULL,
	[1976] [int] NULL,
	[1977] [int] NULL,
	[1978] [int] NULL,
	[1979] [int] NULL,
	[1980] [int] NULL,
	[1981] [int] NULL,
	[1982] [int] NULL,
	[1983] [int] NULL,
	[1984] [int] NULL,
	[1985] [int] NULL,
	[1986] [int] NULL,
	[1987] [int] NULL,
	[1988] [int] NULL,
	[1989] [int] NULL,
	[1990] [int] NULL,
	[1991] [int] NULL,
	[1992] [int] NULL,
	[1993] [int] NULL,
	[1994] [int] NULL,
	[1995] [int] NULL,
	[1996] [int] NULL,
	[1997] [int] NULL,
	[1998] [int] NULL,
	[1999] [int] NULL,
	[2000] [int] NULL,
	[2001] [int] NULL,
	[2002] [int] NULL,
	[2003] [int] NULL,
	[2004] [int] NULL,
	[2005] [int] NULL,
	[2006] [int] NULL,
	[2007] [int] NULL,
	[2008] [int] NULL,
	[2009] [int] NULL,
	[2010] [int] NULL,
	[2011] [int] NULL,
	[2012] [int] NULL,
	[2013] [int] NULL,
	[2014] [int] NULL,
	[2015] [int] NULL,
	[2016] [int] NULL,
	[2017] [int] NULL,
	[2018] [int] NULL,
	[2019] [int] NULL,
	[2020] [int] NULL,
	[2021] [int] NULL,
	[2022] [int] NULL,
	[DEBT] [bigint] NULL
) ON [PRIMARY]
GO

# [international_debt]

In [0]:
USE [master]
GO

In [0]:
ALTER DATABASE [international_debt] SET  READ_WRITE 
GO